export enum GaCustomEvents {
  CREATE_BOOKING = 'create_booking',
  UPDATE_BOOKING = 'update_booking',
  CREATE_BOOKING_PAYMENT = 'create_booking_payment',
  CREATE_CLIENT = 'create_client',
  CREATE_SERVICE = 'create_service',
  CREATE_EXPENSE = 'create_expense',
  CREATE_EXPENSE_PAYMENT = 'create_expense_payment',
  CREATE_SUPPLIER = 'create_supplier',
  UPDATE_REFUND_REQUEST = 'update_refund_request',
  UPDATE_PRICE_REQUEST = 'update_price_request',
  CREATE_NEW_HALL = 'create_new_hall',
  CREATE_EVENT = 'create_event',
  CREATE_ROLE = 'create_role',
  CREATE_EMPLOYEE = 'create_employee',
  CREATE_PAYMENT_METHOD = 'create_payment_method',
  CREATE_EXPENSE_CATEGORY = 'create_expense_category',
  CREATE_EXPENSE_ITEM = 'create_expense_item',
  CREATE_DISCOUNT = 'create_discount',
  CREATE_INVENTORY_ITEM = 'create_inventory_item',
}
